print("=" * 60)
print("🎲 GitHub 盲盒 & 书籍盲盒 & 应用商店")
print("=" * 60)
print()
print("【抽项目】")
print("  抽            随机抽一个 GitHub 项目")
print("  抽热门        从高星项目里抽")
print()
print("【抽 APK】")
print("  抽APK         从所有带 APK 的项目里抽")
print("  抽热门APK     从高星带 APK 的项目里抽")
print("  抽精品        从开箱即用的精品 APK 里抽（推荐）")
print()
print("【抽书】")
print("  抽书          随机抽一本书（中英混合）")
print("  抽书 zh       只抽中文书")
print("  抽书 en       只抽英文书")
print()
print("【下载】")
print("  下APK         下载刚抽到的 APK")
print("  下载书        把刚抽到的书存成 txt")
print()
print("【收藏】")
print("  收藏          收藏刚抽到的项目")
print("  收藏书        收藏刚抽到的书")
print("  收藏夹        查看所有收藏")
print()
print("【查看】")
print("  看APK         列出所有带 APK 的项目")
print()
print("【抓新数据】(需要网络)")
print("  抓            抓新的 GitHub 项目")
print("  抓书          抓新的书籍")
print()
print("=" * 60)
